version: '3.8'

volumes:
  grafana-data:
  prometheus-data:

services:

  iris-api:
    build: ./api
    container_name: iris-api
    ports:
      - '5000:5000'
      - '8001:8001'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/predict || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  drift-compute:
    build: ./drift
    container_name: drift-compute
    depends_on:
      - prometheus
    ports:
      - '8002:8002'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - iris-api
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   # or your chosen password
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: unless-stopped