# PIPELINE DEFINITION
# Name: iris-training-pipeline
components:
  comp-train-model:
    executorLabel: exec-train-model
deploymentSpec:
  executors:
    exec-train-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.13.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_model():\n    import joblib\n    from sklearn.datasets\
          \ import load_iris\n    from sklearn.ensemble import RandomForestClassifier\n\
          \    import os\n\n    iris = load_iris()\n    X, y = iris.data, iris.target\n\
          \n    model = RandomForestClassifier()\n    model.fit(X, y)\n\n    os.makedirs(\"\
          /tmp/model\", exist_ok=True)\n    joblib.dump(model, \"/tmp/model/model.joblib\"\
          )\n    print(\"\u2705 Model saved.\")\n\n"
        image: python:3.9
pipelineInfo:
  name: iris-training-pipeline
root:
  dag:
    tasks:
      train-model:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-model
        taskInfo:
          name: train-model
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
