global:
  scrape_interval: 1s

scrape_configs:
  - job_name: iris-api
    metrics_path: /metrics
    static_configs:
      - targets: ['iris-api:8001']

  - job_name: iris-drift
    metrics_path: /metrics
    static_configs:
      - targets: ['drift-compute:8002']
