apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simple-linear-regression-v1-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2025-06-28T18:57:29.436593',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Trains a model using KFP
      v1 syntax", "name": "Simple Linear Regression v1"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: simple-linear-regression-v1
  templates:
  - name: simple-linear-regression-v1
    dag:
      tasks:
      - {name: train-linear-model, template: train-linear-model}
  - name: train-linear-model
    container:
      args: ['pip install scikit-learn pandas && python -c "import numpy as np; from
          sklearn.linear_model import LinearRegression; X = np.array([[1], [2], [3],
          [4]]); y = np.array([2, 4, 6, 8]); model = LinearRegression().fit(X, y);
          print(''Coefficients:'', model.coef_)"']
      command: [sh, -c]
      image: python:3.9
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
